"""empty message

Revision ID: 026ef8c675a0
Revises: 6e1df75a5980
Create Date: 2024-08-07 10:20:40.480806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026ef8c675a0'
down_revision = '6e1df75a5980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_his', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('old_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_his', schema=None) as batch_op:
        batch_op.drop_column('old_data')
        batch_op.drop_column('data_type')
        batch_op.drop_column('column')

    # ### end Alembic commands ###
