"""empty message

Revision ID: 2f4a4a3386b1
Revises: e27027fda8bb
Create Date: 2024-08-07 08:16:33.844841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4a4a3386b1'
down_revision = 'e27027fda8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images64',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_data', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='fk_project_image64'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images64')
    # ### end Alembic commands ###
