"""Added audio to content

Revision ID: 4d4e0fde9279
Revises: 59ce0c2c8ba9
Create Date: 2024-07-25 10:49:44.680885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4e0fde9279'
down_revision = '59ce0c2c8ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang_from', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('lang_from')

    # ### end Alembic commands ###
