"""Content text to null

Revision ID: 895b099d1095
Revises: 4d4e0fde9279
Create Date: 2024-07-25 11:36:31.165968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895b099d1095'
down_revision = '4d4e0fde9279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
